#!/usr/local/bin/python3
from argparse import ArgumentParser as ap
from generators import get_distributions
from simulate import simulate

# Note:  nargs=1 produces and array where leaving nargs unspecified
# produces a scalar value
p = ap(
	prog="sandbox", epilog="="*60,
	description="NoC random assembly modeling simulation.")

p.add_argument(
	"-w", "--wires", dest="wire_range", nargs=2, type=int, required=True,
	metavar=("{from}", "{to}"), help="Wire count range.")

p.add_argument(
	"-l", "--lengths", dest="length_range", nargs=2, type=int, required=True,
	metavar=("{from}", "{to}"), help="Wire length range.")

p.add_argument(
	"-s", "--step", dest="step", type=int, required=True,
	metavar="{step}", help="Wire count range step size")

p.add_argument(
	"-W", "--width", dest="width", type=int, required=True,
	metavar="{width}", help="Width of the N x N chip to simulate")

p.add_argument(
	"-t", "--trials", dest="trials", type=int, required=True,
	metavar="{trails}", help="Number of trials to run with the given parameters")

p.add_argument(
	"-d", "--dist", dest="distribution", type=str, required=True,
	help="Wire distribution to use.", 
	choices=[k for k in dict(get_distributions())])

p.add_argument(
	"-p", "--params", nargs="*", dest="distribution_parameters", required=False,
	metavar="p", help="Parameters passed to the specified distribution",
	default=[])

simulate(p.parse_args())

